Repository bmw-software-engineering/lobster, pull requests merged in 2024-12, with the labels that each got.

#125 system-test for `lobster-trlc`
  Makefile
  tests-system/lobster-trlc/Makefile
  tests-system/lobster-trlc/rbt-output-file/.gitkeep
  tests-system/lobster-trlc/rbt-output-file/default-scenario/expected-output/.gitignore
  tests-system/lobster-trlc/rbt-output-file/default-scenario/expected-output/exit-code.txt
  tests-system/lobster-trlc/rbt-output-file/default-scenario/expected-output/stdout.txt
  tests-system/lobster-trlc/rbt-output-file/default-scenario/expected-output/trlc.lobster
  tests-system/lobster-trlc/rbt-output-file/default-scenario/input/args.txt
  tests-system/lobster-trlc/rbt-output-file/default-scenario/input/default_file.conf
  tests-system/lobster-trlc/rbt-output-file/default-scenario/input/default_file.rsl
  tests-system/lobster-trlc/rbt-output-file/default-scenario/input/default_file.trlc
  tests-system/lobster-trlc/run_tool_tests.py
Labels: CI

#131 Print all "duplicate definition" errors instead of only the first
  CHANGELOG.md
  lobster/io.py
  lobster/report.py
  lobster/tools/core/report/requirements.trlc
  tests-system/lobster-core/report/rbt-report-input-duplicate-definition/multiple-duplicates/expected-output/exit-code.txt
  tests-system/lobster-core/report/rbt-report-input-duplicate-definition/multiple-duplicates/expected-output/stdout.txt
  tests-system/lobster-core/report/rbt-report-input-duplicate-definition/multiple-duplicates/input/args.txt
  tests-system/lobster-core/report/rbt-report-input-duplicate-definition/multiple-duplicates/input/lobster.config
  tests-system/lobster-core/report/rbt-report-input-duplicate-definition/no-duplicates/expected-output/exit-code.txt
  tests-system/lobster-core/report/rbt-report-input-duplicate-definition/no-duplicates/expected-output/stdout.txt
  tests-system/lobster-core/report/rbt-report-input-duplicate-definition/no-duplicates/input/args.txt
  tests-system/lobster-core/report/rbt-report-input-duplicate-definition/no-duplicates/input/lobster.config
Labels: lobster-core, lobster-codebeamer

#138 Add option to pass parameters to clang tidy
  CHANGELOG.md
  lobster/tools/cpp/cpp.py
Labels: lobster-cpp

#141 LOBSTER Release 0.9.20
  CHANGELOG.md
  lobster/version.py
Labels: CI

#143 Move `run_tool_tests.py` one level up
  Makefile
  tests-system/lobster-trlc/Makefile
  tests-system/run_tool_tests.py
Labels: CI

#116 Lobster-cpptest documentation
  documentation/manual-lobster_cpptest.md
  documentation/manual-lobster_gtest.md
  documentation/user-manual.md
  packages/lobster-tool-cpptest/README.md
Labels: documentation

#129 Feature/lobster version flag for tools
  CHANGELOG.md
  lobster/tool.py
  lobster/tools/codebeamer/codebeamer.py
  lobster/tools/core/ci_report/ci_report.py
  lobster/tools/core/html_report/html_report.py
  lobster/tools/core/online_report/online_report.py
  lobster/tools/core/report/report.py
  lobster/tools/cpp/cpp.py
  lobster/tools/cpptest/cpptest.py
  lobster/tools/gtest/gtest.py
  lobster/tools/python/python.py
  lobster/tools/trlc/trlc.py
  lobster/version.py
Labels: lobster-core, lobster-codebeamer, lobster-cpp, lobster-gtest, lobster-json, lobster-python, lobster-trlc, lobster-cpptest

#147 Supporting Bazel 8 in CI
  tests-integration/projects/basic/Makefile
Labels: CI

#149 Feature/use run tool tests py for all system tests
  .gitignore
  Makefile
  tests-system/Makefile
  tests-system/lobster-json/rbt-dummy/.gitkeep
  tests-system/lobster-python/rbt-dummy/default-scenario/expected-output/basic.lobster
  tests-system/lobster-python/rbt-dummy/default-scenario/expected-output/exit-code.txt
  tests-system/lobster-python/rbt-dummy/default-scenario/expected-output/stderr.txt
  tests-system/lobster-python/rbt-dummy/default-scenario/expected-output/stdout.txt
  tests-system/lobster-python/rbt-dummy/default-scenario/input/args.txt
  tests-system/lobster-python/rbt-dummy/default-scenario/input/basic.py
  tests-system/lobster-trlc/Makefile
  tests-system/lobster-trlc/rbt-output-file/default-scenario/expected-output/stderr.txt
  tests-system/run_tool_tests.py
Labels: CI

#134 Feature/html report UI upgrade
  CHANGELOG.md
  lobster/html/htmldoc.py
  lobster/tools/core/html_report/assets/html_report.css
  lobster/tools/core/html_report/assets/html_report.js
  lobster/tools/core/html_report/html_report.py
  packages/lobster-core/setup.py
  packages/lobster-monolithic/setup.py
Labels: lobster-core

#153 Migrate "basic" system tests of `lobster-json`
  Makefile
  lobster/tools/json/requirements.trlc
  tests-system/.gitignore
  tests-system/lobster-json/Makefile
  tests-system/lobster-json/rbt-name-attribute/attribute-given/expected-output/exit-code.txt
  tests-system/lobster-json/rbt-name-attribute/attribute-given/expected-output/output.lobster
  tests-system/lobster-json/rbt-name-attribute/attribute-given/expected-output/stderr.txt
  tests-system/lobster-json/rbt-name-attribute/attribute-given/expected-output/stdout.txt
  tests-system/lobster-json/rbt-name-attribute/attribute-given/input/args.txt
  tests-system/lobster-json/rbt-name-attribute/attribute-given/input/basic.json
  tests-system/lobster-json/rbt-synthetic-tag-name/README.md
  tests-system/lobster-json/rbt-synthetic-tag-name/flat-input-structure/expected-output/exit-code.txt
  tests-system/lobster-json/rbt-synthetic-tag-name/flat-input-structure/expected-output/output.lobster
  tests-system/lobster-json/rbt-synthetic-tag-name/flat-input-structure/expected-output/stderr.txt
  tests-system/lobster-json/rbt-synthetic-tag-name/flat-input-structure/expected-output/stdout.txt
  tests-system/lobster-json/rbt-synthetic-tag-name/flat-input-structure/input/args.txt
  tests-system/lobster-json/rbt-synthetic-tag-name/flat-input-structure/input/basic.json
  tests-system/lobster-json/rbt-synthetic-tag-name/nested-input-structure/expected-output/exit-code.txt
  tests-system/lobster-json/rbt-synthetic-tag-name/nested-input-structure/expected-output/output.lobster
  tests-system/lobster-json/rbt-synthetic-tag-name/nested-input-structure/expected-output/stderr.txt
  tests-system/lobster-json/rbt-synthetic-tag-name/nested-input-structure/expected-output/stdout.txt
  tests-system/lobster-json/rbt-synthetic-tag-name/nested-input-structure/input/args.txt
  tests-system/lobster-json/rbt-synthetic-tag-name/nested-input-structure/input/one/two/basic.json
  tests-system/run_tool_tests.py
Labels: internal

#154 remove obsolete `.gitignore`
  tests-system/lobster-trlc/rbt-output-file/default-scenario/expected-output/.gitignore
Labels: internal

#155 Add TRLC
  .github/workflows/ci.yml
  Makefile
Labels: internal

#151 Pin Bazel to version 8.0.0 in the CI workflow
  .github/workflows/ci.yml
Labels: internal

#156 Adding css files code to the LOBSTER HTML report
  lobster/html/htmldoc.py
  lobster/tools/core/html_report/html_report.py
Labels: lobster-core

#157 Inject absolute paths into "expected output" files
  tests-system/run_tool_tests.py
Labels: internal

#146 feature: support query string as an argument in lobster codebeamer
  CHANGELOG.md
  lobster/tools/codebeamer/codebeamer.py
  packages/lobster-tool-codebeamer/README.md
  tests-unit/lobster-codebeamer/test_codebeamer.py
Labels: lobster-codebeamer

#158 Missing changes for the lobster-codebeamer supports query string argument
  CHANGELOG.md
  lobster/tools/codebeamer/codebeamer.py
Labels: lobster-codebeamer

#159 LOBSTER Release 0.9.21
  CHANGELOG.md
  lobster/version.py
Labels: internal

#160 Bump version to 0.9.22-dev after release
  CHANGELOG.md
  lobster/version.py
Labels: internal

#140 LOBSTER-Cpptest tool to use configuration files
  lobster/tools/cpptest/cpptest.py
  packages/lobster-tool-cpptest/README.md
  tests-unit/lobster-cpptest/data/cpptest-config_1.yaml
  tests-unit/lobster-cpptest/data/cpptest-config_2.yaml
  tests-unit/lobster-cpptest/test_cpptest.py
Labels: lobster-cpptest

#163 Fix typo
  tests-system/README.md
Labels: internal
