Repository bmw-software-engineering/lobster, pull requests merged in 2024-10, with the labels that each got.

#76 Add new tool `lobster-cpptest`
  lobster-cpptest
  lobster/tools/cpptest/__init__.py
  lobster/tools/cpptest/cpptest.py
  lobster/tools/cpptest/parser/constants.py
  lobster/tools/cpptest/parser/requirements_parser.py
  lobster/tools/cpptest/parser/test_case.py
  packages/lobster-tool-cpptest/Makefile
  packages/lobster-tool-cpptest/README.md
  packages/lobster-tool-cpptest/entrypoints
  packages/lobster-tool-cpptest/requirements
  packages/lobster-tool-cpptest/setup.py
  test-unit/lobster-cpptest/__init__.py
  test-unit/lobster-cpptest/data/test_1.config
  test-unit/lobster-cpptest/data/test_2.config
  test-unit/lobster-cpptest/data/test_case.cpp
  test-unit/lobster-cpptest/test_cpptest.py
Labels: lobster-cpp

#93 Packaging correction of `lobster-cpptest` tool
  Makefile
  lobster/tools/cpptest/parser/__init__.py
  lobster/tools/cpptest/parser/constants.py
  lobster/tools/cpptest/parser/requirements_parser.py
  lobster/tools/cpptest/parser/test_case.py
  packages/lobster-tool-cpptest/setup.py
  requirements_dev.txt
Labels: lobster-cpptest

#70 `lobster-codebeamer` uses authentication token
  CHANGELOG.md
  lobster/tools/codebeamer/codebeamer.py
  packages/lobster-tool-codebeamer/README.md
Labels: lobster-codebeamer

#95 Make `lobster-cpptest` executable
  lobster-cpptest
Labels: bug, lobster-cpptest

#90 Added first requirement for `lobster-trlc`
  lobster/tools/trlc/requirements.rsl
  lobster/tools/trlc/requirements.trlc
  lobster/tools/trlc/trlc.py
Labels: documentation

#104 specifies github runner images explicitly
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/package.yml
Labels: CI

#105 Add known issue to `lobster-python` readme
  packages/lobster-tool-python/README.md
Labels: documentation, lobster-python

#88 Add coding guideline
  CODING_GUIDELINE.md
  README.md
  pylint3.cfg
Labels: documentation

#103 Catch `UnicodeDecodeError` in `lobster-json`
  lobster/tools/json/json.py
  setup.cfg
Labels: lobster-json

#106 LOBSTER Release 0.9.18
  CHANGELOG.md
  README.md
  lobster/version.py
Labels: documentation

#107 Bump version to 1.0.0-dev after release
  CHANGELOG.md
  lobster/version.py
  packages/lobster-metapackage/README.md
Labels: CI

#110 fixes dependencies in metapackage when building wheel file
  .github/workflows/package.yml
  CHANGELOG.md
  lobster/version.py
  packages/lobster-core/Makefile
  packages/lobster-metapackage/Makefile
  packages/lobster-monolithic/Makefile
  packages/lobster-tool-codebeamer/Makefile
  packages/lobster-tool-cpp/Makefile
  packages/lobster-tool-cpptest/Makefile
  packages/lobster-tool-gtest/Makefile
  packages/lobster-tool-json/Makefile
  packages/lobster-tool-python/Makefile
  packages/lobster-tool-python/README.md
  packages/lobster-tool-trlc/Makefile
Labels: CI

#74 Unit test/items py
  lobster/tools/python/python.py
  test-system/lobster-python/basic.output
  test-system/lobster-python/multiple_identical_function_names.output
  test-system/lobster-python/pytest_mark.output
  test-unit/test_items.py
Labels: CI

#79 Support different schemas
  CHANGELOG.md
  lobster/tools/codebeamer/codebeamer.py
  packages/lobster-tool-codebeamer/README.md
  test-unit/lobster-codebeamer/__init__.py
  test-unit/lobster-codebeamer/test_codebeamer_schema.py
Labels: bug, lobster-codebeamer

#84 Unit test/io py
  test-unit/test_io.py
Labels: lobster-core
