Repository bmw-software-engineering/lobster, pull requests merged in 2024-11, with the labels that each got.

#113 Add make tracing for TRCL tool
  .github/workflows/docs.yml
  Makefile
  README.md
  lobster/tools/lobster-trlc.conf
  lobster/tools/lobster.conf
  lobster/tools/requirements.rsl
  lobster/tools/trlc/requirements.trlc
  lobster/tools/trlc/trlc.py
  test-system/lobster-trlc/lobster-trlc-system-test.py
  test-system/lobster-trlc/rbt-output-file/.gitkeep
  test-unit/lobster-trlc/.gitkeep
Labels: lobster-trlc, CI

#118 Update TRLC version to 2.0.0
  requirements.txt
Labels: lobster-trlc, CI

#117 Typo fix in error message
  lobster/tools/trlc/trlc.py
Labels: documentation, lobster-trlc

#119 Updated CHANGELOG
  CHANGELOG.md
Labels: documentation

#128 Activate pylint for `util` files
  Makefile
  util/bump_version_post_release.py
  util/changelog.py
  util/github_release.py
  util/mkassets.py
  util/release.py
Labels: CI

#123 Dfm/parametrize make tracing tools
  Makefile
  README.md
  lobster-ci-report
  lobster-html-report
  lobster-online-report
  lobster-report
  lobster/tools/codebeamer/codebeamer.py
  lobster/tools/codebeamer/requirements.trlc
  lobster/tools/core/ci_report/__init__.py
  lobster/tools/core/ci_report/ci_report.py
  lobster/tools/core/ci_report/requirements.trlc
  lobster/tools/core/html_report/__init__.py
  lobster/tools/core/html_report/html_report.py
  lobster/tools/core/html_report/requirements.trlc
  lobster/tools/core/online_report/__init__.py
  lobster/tools/core/online_report/online_report.py
  lobster/tools/core/online_report/requirements.trlc
  lobster/tools/core/report/__init__.py
  lobster/tools/core/report/report.py
  lobster/tools/core/report/requirements.trlc
  lobster/tools/cpp/cpp.py
  lobster/tools/cpp/requirements.trlc
  lobster/tools/cpptest/cpptest.py
  lobster/tools/cpptest/requirements.trlc
  lobster/tools/gtest/gtest.py
  lobster/tools/gtest/requirements.trlc
  lobster/tools/json/json.py
  lobster/tools/json/requirements.trlc
  lobster/tools/lobster-trlc.conf
  lobster/tools/python/python.py
  lobster/tools/python/requirements.trlc
  lobster/tools/requirements.rsl
  lobster/tools/trlc/requirements.trlc
  packages/lobster-core/setup.py
  packages/lobster-monolithic/setup.py
  tests-system/lobster-codebeamer/rbt-output-file/.gitkeep
  tests-system/lobster-core/ci_report/rbt-output-file/.gitkeep
  tests-system/lobster-core/html_report/rbt-output-file/.gitkeep
  tests-system/lobster-core/online_report/rbt-output-file/.gitkeep
  tests-system/lobster-core/report/rbt-output-file/.gitkeep
  tests-system/lobster-cpp/rbt-output-file/.gitkeep
  tests-system/lobster-cpptest/rbt-output-file/.gitkeep
  tests-system/lobster-gtest/rbt-output-file/.gitkeep
  tests-system/lobster-json/Makefile
  tests-system/lobster-json/rbt-output-file/.gitkeep
  tests-system/lobster-python/Makefile
  tests-system/lobster-python/rbt-output-file/.gitkeep
  tests-system/lobster-trlc-system-test.py
  tests-unit/lobster-codebeamer/test_codebeamer.py
  tests-unit/lobster-codebeamer/test_codebeamer_schema.py
  tests-unit/lobster-core/ci_report/test_ci_report.py
  tests-unit/lobster-core/html_report/test_html_report.py
  tests-unit/lobster-core/online_report/test_online_report.py
  tests-unit/lobster-core/report/test_report.py
  tests-unit/lobster-cpp/.gitkeep
  tests-unit/lobster-cpptest/test_cpptest.py
  tests-unit/lobster-gtest/.gitkeep
  tests-unit/lobster-json/.gitkeep
  tests-unit/lobster-python/.gitkeep
Labels: CI

#130 Silently skip unrelated gtest XML entries
  lobster/tools/gtest/gtest.py
Labels: lobster-gtest

#132 Update changelog
  CHANGELOG.md
Labels: documentation
