Repository bmw-software-engineering/lobster, pull requests merged in 2025-02, with the labels that each got.

#192 Remove hard-coded file name `requirements.trlc` from `make tracing`
  Makefile
Labels: internal

#189 System tests for `lobster-json`
  .gitignore
  lobster/tools/json/input_files.trlc
  lobster/tools/json/software_requirements.trlc
  lobster/tools/json/synthetic_name.trlc
  lobster/tools/json/system_requirements.trlc
  lobster/tools/lobster-trlc.conf
  lobster/tools/requirements.rsl
  tests-system/.gitignore
  tests-system/lobster-json/rbt-name-attribute-missing/README.md
  tests-system/lobster-json/rbt-name-attribute-missing/flat-input-structure/expected-output/exit-code.txt
  tests-system/lobster-json/rbt-name-attribute-missing/flat-input-structure/expected-output/output.lobster
  tests-system/lobster-json/rbt-name-attribute-missing/flat-input-structure/expected-output/stderr.txt
  tests-system/lobster-json/rbt-name-attribute-missing/flat-input-structure/expected-output/stdout.txt
  tests-system/lobster-json/rbt-name-attribute-missing/flat-input-structure/input/args.txt
  tests-system/lobster-json/rbt-name-attribute-missing/flat-input-structure/input/basic.json
  tests-system/lobster-json/rbt-name-attribute-missing/nested-input-structure/expected-output/exit-code.txt
  tests-system/lobster-json/rbt-name-attribute-missing/nested-input-structure/expected-output/output.lobster
  tests-system/lobster-json/rbt-name-attribute-missing/nested-input-structure/expected-output/stderr.txt
  tests-system/lobster-json/rbt-name-attribute-missing/nested-input-structure/expected-output/stdout.txt
  tests-system/lobster-json/rbt-name-attribute-missing/nested-input-structure/input/args.txt
  tests-system/lobster-json/rbt-name-attribute-missing/nested-input-structure/input/one/two/basic.json
  tests-system/lobster-json/rbt-parse-input-file-json-extension/invalid-json-file-extension/README.md
  tests-system/lobster-json/rbt-parse-input-file-json-extension/invalid-json-file-extension/expected-output/exit-code.txt
  tests-system/lobster-json/rbt-parse-input-file-json-extension/invalid-json-file-extension/expected-output/output.lobster
  tests-system/lobster-json/rbt-parse-input-file-json-extension/invalid-json-file-extension/expected-output/stderr.txt
  tests-system/lobster-json/rbt-parse-input-file-json-extension/invalid-json-file-extension/expected-output/stdout.txt
  tests-system/lobster-json/rbt-parse-input-file-json-extension/invalid-json-file-extension/input/args.txt
  tests-system/lobster-json/rbt-parse-input-file-json-extension/invalid-json-file-extension/input/data.invalidjson
  tests-system/lobster-json/rbt-parse-input-file-json-extension/mixed-extensions/README.md
  tests-system/lobster-json/rbt-parse-input-file-json-extension/mixed-extensions/expected-output/exit-code.txt
  tests-system/lobster-json/rbt-parse-input-file-json-extension/mixed-extensions/expected-output/output.lobster
  tests-system/lobster-json/rbt-parse-input-file-json-extension/mixed-extensions/expected-output/stderr.txt
  tests-system/lobster-json/rbt-parse-input-file-json-extension/mixed-extensions/expected-output/stdout.txt
  tests-system/lobster-json/rbt-parse-input-file-json-extension/mixed-extensions/input/args.txt
  tests-system/lobster-json/rbt-parse-input-file-json-extension/mixed-extensions/input/data.invalidjson
  tests-system/lobster-json/rbt-parse-input-file-json-extension/mixed-extensions/input/valid.json
  tests-system/lobster-json/rbt-parse-input-file/file-does-not-exist/README.md
  tests-system/lobster-json/rbt-parse-input-file/file-does-not-exist/expected-output/exit-code.txt
  tests-system/lobster-json/rbt-parse-input-file/file-does-not-exist/expected-output/stderr.txt
  tests-system/lobster-json/rbt-parse-input-file/file-does-not-exist/expected-output/stdout.txt
  tests-system/lobster-json/rbt-parse-input-file/file-does-not-exist/input/args.txt
Labels: internal

#194 Adjust LOBSTER tracing policy
  Makefile
  lobster/tools/lobster-trlc-software.conf
  lobster/tools/lobster-trlc-system.conf
  lobster/tools/lobster.conf
  tests-system/lobster-ci-report/rbt-output-file/.gitkeep
  tests-system/lobster-core/html_report/selenium-test/test_html_report.html
  tests-system/lobster-core/online_report/rbt-output-file/.gitkeep
  tests-system/lobster-html-report/rbt-output-file/.gitkeep
  tests-system/lobster-html-report/selenium-test/test_html_report.py
  tests-system/lobster-online-report/rbt-valid-flow/valid-scenario/expected-output/expected-output.lobster
  tests-system/lobster-trlc-system-test.py
Labels: internal

#171 Requirements for trace-to
  lobster/tools/core/report/requirements.trlc
  tests-system/lobster-online-report/rbt-valid-flow/valid-scenario/expected-output/expected-output.lobster
  tests-system/lobster-report/rbt-missing-reference/missing/expected-output/exit-code.txt
  tests-system/lobster-report/rbt-missing-reference/missing/expected-output/report.lobster
  tests-system/lobster-report/rbt-missing-reference/missing/expected-output/stderr.txt
  tests-system/lobster-report/rbt-missing-reference/missing/expected-output/stdout.txt
  tests-system/lobster-report/rbt-missing-reference/missing/input/args.txt
  tests-system/lobster-report/rbt-missing-reference/missing/input/lobster.conf
  tests-system/lobster-report/rbt-missing-reference/missing/input/python.output
  tests-system/lobster-report/rbt-missing-reference/missing/input/trlc.output
  tests-system/lobster-report/rbt-missing-reference/mixed-single-file/expected-output/exit-code.txt
  tests-system/lobster-report/rbt-missing-reference/mixed-single-file/expected-output/report.lobster
  tests-system/lobster-report/rbt-missing-reference/mixed-single-file/expected-output/stderr.txt
  tests-system/lobster-report/rbt-missing-reference/mixed-single-file/expected-output/stdout.txt
  tests-system/lobster-report/rbt-missing-reference/mixed-single-file/input/args.txt
  tests-system/lobster-report/rbt-missing-reference/mixed-single-file/input/lobster.conf
  tests-system/lobster-report/rbt-missing-reference/mixed-single-file/input/python.output
  tests-system/lobster-report/rbt-missing-reference/mixed-single-file/input/trlc.output
  tests-system/lobster-report/rbt-status-ok/all/expected-output/exit-code.txt
  tests-system/lobster-report/rbt-status-ok/all/expected-output/report.lobster
  tests-system/lobster-report/rbt-status-ok/all/expected-output/stderr.txt
  tests-system/lobster-report/rbt-status-ok/all/expected-output/stdout.txt
  tests-system/lobster-report/rbt-status-ok/all/input/args.txt
  tests-system/lobster-report/rbt-status-ok/all/input/lobster.conf
  tests-system/lobster-report/rbt-status-ok/all/input/python.output
  tests-system/lobster-report/rbt-status-ok/all/input/trlc.output
Labels: internal

#196 Compute coverage of all files
  Makefile
  coverage.cfg
  tests-system/run_tool_tests.py
Labels: internal

#199 Write requirements and system tests for `lobster-json`
  lobster/tools/REQUIREMENTS.md
  lobster/tools/json/input_files.trlc
  lobster/tools/json/input_not_file_not_directory.trlc
  lobster/tools/lobster-trlc-system.conf
  lobster/tools/lobster.conf
  lobster/tools/requirements.rsl
  tests-system/lobster-json/rbt-input-file-json-extension/README.md
  tests-system/lobster-json/rbt-input-file-json-extension/mixed-extensions/expected-output/exit-code.txt
  tests-system/lobster-json/rbt-input-file-json-extension/mixed-extensions/expected-output/output.lobster
  tests-system/lobster-json/rbt-input-file-json-extension/mixed-extensions/expected-output/stderr.txt
  tests-system/lobster-json/rbt-input-file-json-extension/mixed-extensions/expected-output/stdout.txt
  tests-system/lobster-json/rbt-input-file-json-extension/mixed-extensions/input/args.txt
  tests-system/lobster-json/rbt-input-file-json-extension/mixed-extensions/input/data.json
  tests-system/lobster-json/rbt-input-file-json-extension/mixed-extensions/input/data.txt
  tests-system/lobster-json/rbt-input-file-json-extension/single-other-extension/expected-output/exit-code.txt
  tests-system/lobster-json/rbt-input-file-json-extension/single-other-extension/expected-output/output.lobster
  tests-system/lobster-json/rbt-input-file-json-extension/single-other-extension/expected-output/stderr.txt
  tests-system/lobster-json/rbt-input-file-json-extension/single-other-extension/expected-output/stdout.txt
  tests-system/lobster-json/rbt-input-file-json-extension/single-other-extension/input/args.txt
  tests-system/lobster-json/rbt-input-file-json-extension/single-other-extension/input/data.txt
  tests-system/lobster-json/rbt-input-not-file-not-directory/README.md
  tests-system/lobster-json/rbt-input-not-file-not-directory/nothing-exists/expected-output/exit-code.txt
  tests-system/lobster-json/rbt-input-not-file-not-directory/nothing-exists/expected-output/stderr.txt
  tests-system/lobster-json/rbt-input-not-file-not-directory/nothing-exists/expected-output/stdout.txt
  tests-system/lobster-json/rbt-input-not-file-not-directory/nothing-exists/input/args.txt
  tests-system/lobster-json/rbt-input-not-file-not-directory/one-file-exists/expected-output/exit-code.txt
  tests-system/lobster-json/rbt-input-not-file-not-directory/one-file-exists/expected-output/stderr.txt
  tests-system/lobster-json/rbt-input-not-file-not-directory/one-file-exists/expected-output/stdout.txt
  tests-system/lobster-json/rbt-input-not-file-not-directory/one-file-exists/input/args.txt
  tests-system/lobster-json/rbt-input-not-file-not-directory/one-file-exists/input/file_exists.json
  tests-system/lobster-json/rbt-parse-input-file-json-extension/invalid-json-file-extension/README.md
  tests-system/lobster-json/rbt-parse-input-file-json-extension/invalid-json-file-extension/input/args.txt
  tests-system/lobster-json/rbt-parse-input-file-json-extension/invalid-json-file-extension/input/data.invalidjson
  tests-system/lobster-json/rbt-parse-input-file-json-extension/mixed-extensions/README.md
  tests-system/lobster-json/rbt-parse-input-file-json-extension/mixed-extensions/input/args.txt
  tests-system/lobster-json/rbt-parse-input-file-json-extension/mixed-extensions/input/data.invalidjson
  tests-system/lobster-json/rbt-parse-input-file-json-extension/mixed-extensions/input/valid.json
  tests-system/lobster-json/rbt-parse-input-file/file-does-not-exist/README.md
  tests-system/lobster-json/rbt-parse-input-file/file-does-not-exist/input/args.txt
Labels: internal

#203 Fix unit test folder structure
  Makefile
  tests-unit/lobster-ci-report/test_ci_report.py
  tests-unit/lobster-core/online_report/__init__.py
  tests-unit/lobster-html-report/__init__.py
  tests-unit/lobster-html-report/test_html_report.py
  tests-unit/lobster-online-report/__init__.py
  tests-unit/lobster-online-report/data/basic.py
  tests-unit/lobster-online-report/data/report-lobster.output
  tests-unit/lobster-online-report/test_online_report.py
  tests-unit/lobster-report/test_report.py
Labels: internal

#201 Removed /cb from the codebeamer api call, added unit tests, modified …
  CHANGELOG.md
  documentation/manual-lobster_codebeamer.md
  lobster/tools/codebeamer/codebeamer.py
  tests-unit/lobster-codebeamer/test_codebeamer.py
Labels: documentation, lobster-codebeamer

#206 Simplify error handling if input is missing for `lobster-html-report`
  CHANGELOG.md
  Makefile
  lobster/tools/core/html_report/html_report.py
  lobster/tools/core/html_report/input_file_existance.trlc
  tests-system/.gitignore
  tests-system/lobster-html-report/rbt-input-file-existance/README.txt
  tests-system/lobster-html-report/rbt-input-file-existance/is-file/README.md
  tests-system/lobster-html-report/rbt-input-file-existance/is-file/expected-output/exit-code.txt
  tests-system/lobster-html-report/rbt-input-file-existance/is-file/expected-output/is_actually_html.lobster
  tests-system/lobster-html-report/rbt-input-file-existance/is-file/expected-output/stderr.txt
  tests-system/lobster-html-report/rbt-input-file-existance/is-file/expected-output/stdout.txt
  tests-system/lobster-html-report/rbt-input-file-existance/is-file/input/args.txt
  tests-system/lobster-html-report/rbt-input-file-existance/is-file/input/awesome.lobster
  tests-system/lobster-html-report/rbt-input-file-existance/is-not-file/expected-output/exit-code.txt
  tests-system/lobster-html-report/rbt-input-file-existance/is-not-file/expected-output/stderr.txt
  tests-system/lobster-html-report/rbt-input-file-existance/is-not-file/expected-output/stdout.txt
  tests-system/lobster-html-report/rbt-input-file-existance/is-not-file/input/args.txt
Labels: lobster-core

#205 Make `valid_status` constraint optional
  CHANGELOG.md
  lobster/items.py
Labels: lobster-core

#209 Include lobster-rust in README.
  README.md
Labels: documentation

#208 Renamed Search to Filter in HTML report
  CHANGELOG.md
  lobster/tools/core/html_report/html_report.py
  tests-system/lobster-html-report/rbt-input-file-existance/is-file/expected-output/is_actually_html.lobster
Labels: lobster-html-report

#211 Refactor requirement missing_reference for lobster-report
  lobster/tools/core/report/requirements.trlc
  tests-system/lobster-report/rbt-status-missing/missing/expected-output/exit-code.txt
  tests-system/lobster-report/rbt-status-missing/missing/expected-output/report.lobster
  tests-system/lobster-report/rbt-status-missing/missing/expected-output/stderr.txt
  tests-system/lobster-report/rbt-status-missing/missing/expected-output/stdout.txt
  tests-system/lobster-report/rbt-status-missing/missing/input/args.txt
  tests-system/lobster-report/rbt-status-missing/missing/input/lobster.conf
  tests-system/lobster-report/rbt-status-missing/missing/input/python.output
  tests-system/lobster-report/rbt-status-missing/missing/input/trlc.output
  tests-system/lobster-report/rbt-status-missing/mixed-single-file/expected-output/exit-code.txt
  tests-system/lobster-report/rbt-status-missing/mixed-single-file/expected-output/report.lobster
  tests-system/lobster-report/rbt-status-missing/mixed-single-file/expected-output/stderr.txt
  tests-system/lobster-report/rbt-status-missing/mixed-single-file/expected-output/stdout.txt
  tests-system/lobster-report/rbt-status-missing/mixed-single-file/input/args.txt
  tests-system/lobster-report/rbt-status-missing/mixed-single-file/input/lobster.conf
  tests-system/lobster-report/rbt-status-missing/mixed-single-file/input/python.output
  tests-system/lobster-report/rbt-status-missing/mixed-single-file/input/trlc.output
Labels: internal

#204 Call `close()` and `join()` on `multiprocessing.Pool()`
  CHANGELOG.md
  lobster/tool.py
Labels: lobster-json, internal

#210 Removed "commit" from lobster-online-report tool
  CHANGELOG.md
  documentation/schemas.md
  lobster/location.py
  lobster/tools/core/html_report/html_report.py
  lobster/tools/core/online_report/online_report.py
  tests-UI/report.output
  tests-UI/report_test/test_html_report.py
  tests-integration/projects/basic/report.reference_output
  tests-integration/projects/filter/report.reference_output
  tests-system/.gitignore
  tests-system/lobster-online-report/rbt-valid-flow/valid-scenario/expected-output/expected-output.lobster
  tests-system/lobster-online-report/rbt-valid-flow/valid-scenario/input/report.lobster
  tests-system/tests_utils/update_online_json_with_hashes.py
  tests-unit/lobster-online-report/test_online_report.py
  tests-unit/test_items.py
Labels: documentation, lobster-online-report

#202 cmd-config-for-lobster-tool-class
  CHANGELOG.md
  lobster/tool.py
  packages/lobster-tool-json/README.md
  tests-integration/projects/basic/Makefile
  tests-integration/projects/basic/config.yaml
  tests-integration/projects/filter/Makefile
  tests-integration/projects/filter/config.yaml
  tests-system/lobster-json/rbt-input-file-json-extension/mixed-extensions/expected-output/stdout.txt
  tests-system/lobster-json/rbt-input-file-json-extension/mixed-extensions/input/args.txt
  tests-system/lobster-json/rbt-input-file-json-extension/mixed-extensions/input/config.yaml
  tests-system/lobster-json/rbt-input-file-json-extension/single-other-extension/expected-output/stdout.txt
  tests-system/lobster-json/rbt-input-file-json-extension/single-other-extension/input/args.txt
  tests-system/lobster-json/rbt-input-file-json-extension/single-other-extension/input/config.yaml
  tests-system/lobster-json/rbt-input-not-file-not-directory/nothing-exists/expected-output/stdout.txt
  tests-system/lobster-json/rbt-input-not-file-not-directory/nothing-exists/input/args.txt
  tests-system/lobster-json/rbt-input-not-file-not-directory/nothing-exists/input/config.yaml
  tests-system/lobster-json/rbt-input-not-file-not-directory/one-file-exists/expected-output/stdout.txt
  tests-system/lobster-json/rbt-input-not-file-not-directory/one-file-exists/input/args.txt
  tests-system/lobster-json/rbt-input-not-file-not-directory/one-file-exists/input/config.yaml
  tests-system/lobster-json/rbt-name-attribute-missing/flat-input-structure/input/args.txt
  tests-system/lobster-json/rbt-name-attribute-missing/flat-input-structure/input/config.yaml
  tests-system/lobster-json/rbt-name-attribute-missing/nested-input-structure/input/args.txt
  tests-system/lobster-json/rbt-name-attribute-missing/nested-input-structure/input/config.yaml
  tests-system/lobster-json/rbt-name-attribute/attribute-given/input/args.txt
  tests-system/lobster-json/rbt-name-attribute/attribute-given/input/config.yaml
  tests-unit/test_tool.py
Labels: documentation, lobster-json

#218 Allow `--out` command line argument in lobster tool base class
  CHANGELOG.md
  lobster/tool.py
Labels: lobster-json

#219 Increase mandatory TRLC version to `2.0.1`
  CHANGELOG.md
  requirements.txt
Labels: lobster-trlc

#220 Add `.vscode` to `.gitignore`
  .gitignore
Labels: internal

#217 document updated for codebeamer auth
  Makefile
  documentation/manual-lobster_codebeamer.md
  lobster/tools/codebeamer/codebeamer.py
  packages/lobster-tool-codebeamer/README.md
  tests-unit/lobster-codebeamer/test_codebeamer_schema.py
Labels: lobster-codebeamer

#221 Include dependency to `PyYAML` in `requirements.txt`
  CHANGELOG.md
  requirements.txt
Labels: lobster-core, lobster-codebeamer, lobster-cpp, lobster-gtest, lobster-json, lobster-python, lobster-trlc, lobster-cpptest, lobster-html-report, lobster-online-report
