Repository bmw-software-engineering/lobster, pull requests merged in 2025-04, with the labels that each got.

#256 Remove the tool lobster-report from old STF
  Makefile
Labels: internal

#266 Removed lobster-trlc system test: default-scenario
  Makefile
  tests-system/.gitignore
  tests-system/lobster-trlc/rbt-output-file/default-scenario/expected-output/exit-code.txt
  tests-system/lobster-trlc/rbt-output-file/default-scenario/expected-output/stderr.txt
  tests-system/lobster-trlc/rbt-output-file/default-scenario/expected-output/stdout.txt
  tests-system/lobster-trlc/rbt-output-file/default-scenario/expected-output/trlc.lobster
  tests-system/lobster-trlc/rbt-output-file/default-scenario/input/args.txt
  tests-system/lobster-trlc/rbt-output-file/default-scenario/input/default_file.conf
  tests-system/lobster-trlc/rbt-output-file/default-scenario/input/default_file.rsl
  tests-system/lobster-trlc/rbt-output-file/default-scenario/input/default_file.trlc
  tests-system/lobster-trlc/rbt-output-file/default-scenario/input/trlc_config.yaml
Labels: internal

#267 Add command line argument `skip-clang-errors` to `lobster-cpp`
  CHANGELOG.md
  documentation/manual-lobster_cpp.md
  documentation/user-manual.md
  lobster/tools/cpp/cpp.py
Labels: lobster-cpp

#269 System tests specify custom temp directory path
  tests-system/system_test_case_base.py
Labels: internal

#253 Fix BMW copyright dates
  lobster/config/lexer.py
  lobster/config/parser.py
  lobster/html/htmldoc.py
  lobster/items.py
  lobster/report.py
  lobster/tools/core/ci_report/ci_report.py
  lobster/tools/core/html_report/html_report.py
  lobster/tools/core/online_report/online_report.py
  lobster/tools/core/report/report.py
  lobster/tools/cpp/cpp.py
  lobster/tools/cpptest/cpptest.py
  lobster/tools/gtest/gtest.py
  lobster/tools/trlc/trlc.py
  lobster/version.py
  util/bump_version_post_release.py
  util/changelog.py
  util/github_release.py
  util/mkassets.py
  util/release.py
Labels: internal

#261 Feature: lobster-cpptest has test-name in tag
  CHANGELOG.md
  lobster/tools/cpptest/cpptest.py
  packages/lobster-tool-cpptest/README.md
  tests-unit/lobster-cpptest/test_cpptest.py
Labels: internal

#272 More precisely CB url in documentation
  documentation/manual-lobster_cpptest.md
Labels: documentation

#257 Precise summary message of `lobster-online-report`
  CHANGELOG.md
  lobster/tools/core/online_report/online_report.py
  tests-system/lobster-online-report/rbt-valid-flow/valid-scenario/expected-output/stdout.txt
  tests-unit/lobster-online-report/test_online_report.py
Labels: lobster-online-report

#268 use file path to generate UID in `lobster-cpp`
  CHANGELOG.md
  lobster/tools/cpp/cpp.py
Labels: lobster-cpp

#258 Move authentication provision into separate function
  lobster/tools/codebeamer/bearer_auth.py
  lobster/tools/codebeamer/codebeamer.py
  tests-unit/lobster-codebeamer/test_authentication.py
Labels: lobster-codebeamer, internal

#213 Delete unnecessary file content
  tests-system/lobster-online-report/rbt-valid-flow/valid-scenario/input/basic.py
Labels: internal

#236 lobster-online-report: migrate existing system test to new infra
  lobster/tools/core/online_report/requirements.trlc
  tests-system/lobster-online-report/data/basic.py
  tests-system/lobster-online-report/data/expected-output.lobster
  tests-system/lobster-online-report/data/report.lobster
  tests-system/lobster-online-report/lobster_online_report_system_test_case_base.py
  tests-system/lobster-online-report/rbt-valid-flow/valid-scenario/expected-output/exit-code.txt
  tests-system/lobster-online-report/rbt-valid-flow/valid-scenario/expected-output/stderr.txt
  tests-system/lobster-online-report/rbt-valid-flow/valid-scenario/expected-output/stdout.txt
  tests-system/lobster-online-report/rbt-valid-flow/valid-scenario/input/args.txt
  tests-system/lobster-online-report/test_git_repository.py
  tests-system/lobster-online-report/test_invalid_git_repository.py
  tests-system/tests_utils/update_online_json_with_hashes.py
Labels: internal

#283 Optimize calls to git in lobster-online-report
  lobster/tools/core/online_report/online_report.py
  tests-unit/lobster-online-report/test_online_report.py
Labels: internal

#281 lobster-cpptest: Change orphan test handling.
  CHANGELOG.md
  documentation/manual-lobster_cpptest.md
  lobster/tools/cpptest/cpptest.py
  tests-unit/lobster-cpptest/data/cpptest-config_1.yaml
  tests-unit/lobster-cpptest/data/cpptest-config_2.yaml
  tests-unit/lobster-cpptest/test_cpptest.py
Labels: lobster-cpptest

#282 Editorial changes of use cases
  lobster/tools/UseCase.trlc
  lobster/tools/requirements.rsl
  lobster/tools/use_cases_nice_to_have.trlc
  lobster/use_cases.trlc
Labels: documentation

#284 retry logic for lobster-codebeamer
  CHANGELOG.md
  documentation/manual-lobster_codebeamer.md
  lobster/tools/codebeamer/codebeamer.py
  lobster/tools/codebeamer/config.py
  lobster/tools/codebeamer/requirements.trlc
  tests-system/.gitignore
  tests-system/lobster-codebeamer/data/codebeamer-config-retry-configured.yaml
  tests-system/lobster-codebeamer/data/codebeamer-config-retry-not_configured.yaml
  tests-system/lobster-codebeamer/mock_server.py
  tests-system/lobster-codebeamer/test_lobster_codebeamer.py
  tests-system/lobster-codebeamer/test_valid_scenario.py
  tests-unit/lobster-codebeamer/test_codebeamer.py
Labels: lobster-codebeamer

#286 Bump version to 0.12.2-dev after release
  CHANGELOG.md
  lobster/version.py
Labels: internal
