Repository bmw-software-engineering/lobster, pull requests merged in 2025-01, with the labels that each got.

#148 selenium system test into CI for html_report
  .github/workflows/ci.yml
  Makefile
  documentation/selenium_into_CI.md
  tests-system/lobster-core/html_report/selenium-test/test_html_report.html
  tests-system/lobster-core/html_report/selenium-test/test_html_report.py
Labels: internal

#167 Update `lobster-codebeamer` documentation
  lobster/tools/codebeamer/codebeamer.py
Labels: documentation

#137 LOBSTER-Codebeamer tool to use configuration files
  CHANGELOG.md
  lobster/tools/codebeamer/codebeamer.py
  packages/lobster-tool-codebeamer/README.md
  tests-unit/lobster-codebeamer/test_codebeamer_schema.py
Labels: lobster-codebeamer

#178 Add the git ignore for .lobster files in tests-system input folder
  tests-system/.gitignore
  tests-system/lobster-report/rbt-report-test/report-test/expected-output/report.lobster
  tests-system/lobster-report/rbt-report-test/report-test/input/lobster.conf
  tests-system/lobster-report/rbt-report-test/report-test/input/python.lobster
  tests-system/lobster-report/rbt-report-test/report-test/input/trlc.lobster
Labels: internal

#174 Make Selenium tests depending on lint+trlc
  .github/workflows/ci.yml
Labels: internal

#175 Catch yaml `ScannerError`
  lobster/tools/cpptest/cpptest.py
Labels: lobster-cpptest

#172 Fix various `README.md` files
  README.md
  packages/lobster-core/README.md
  packages/lobster-tool-cpptest/README.md
Labels: documentation

#176 Add selenium dependencies to `requirements_dev.txt`
  .github/workflows/ci.yml
  requirements_dev.txt
Labels: internal

#183 Fix system test `rbt-report-input-duplicate-definition`
  Makefile
  tests-system/lobster-core/report/rbt-report-input-duplicate-definition/multiple-duplicates/input/args.txt
  tests-system/lobster-core/report/rbt-report-input-duplicate-definition/no-duplicates/input/args.txt
  tests-system/lobster-report/rbt-report-input-duplicate-definition/multiple-duplicates/expected-output/exit-code.txt
  tests-system/lobster-report/rbt-report-input-duplicate-definition/multiple-duplicates/expected-output/stderr.txt
  tests-system/lobster-report/rbt-report-input-duplicate-definition/multiple-duplicates/expected-output/stdout.txt
  tests-system/lobster-report/rbt-report-input-duplicate-definition/multiple-duplicates/input/args.txt
  tests-system/lobster-report/rbt-report-input-duplicate-definition/multiple-duplicates/input/file.lobster
  tests-system/lobster-report/rbt-report-input-duplicate-definition/multiple-duplicates/input/lobster.config
  tests-system/lobster-report/rbt-report-input-duplicate-definition/no-duplicates/expected-output/exit-code.txt
  tests-system/lobster-report/rbt-report-input-duplicate-definition/no-duplicates/expected-output/report.lobster
  tests-system/lobster-report/rbt-report-input-duplicate-definition/no-duplicates/expected-output/stderr.txt
  tests-system/lobster-report/rbt-report-input-duplicate-definition/no-duplicates/expected-output/stdout.txt
  tests-system/lobster-report/rbt-report-input-duplicate-definition/no-duplicates/input/args.txt
  tests-system/lobster-report/rbt-report-input-duplicate-definition/no-duplicates/input/file.lobster
  tests-system/lobster-report/rbt-report-input-duplicate-definition/no-duplicates/input/lobster.config
  tests-system/run_tool_tests.py
Labels: internal

#165 Git hashs in lobster online report output file
  .github/workflows/ci.yml
  CHANGELOG.md
  Makefile
  documentation/schemas.md
  lobster/location.py
  lobster/tools/core/html_report/html_report.py
  lobster/tools/core/online_report/online_report.py
  tests-integration/projects/basic/Makefile
  tests-integration/projects/basic/report.reference_output
  tests-integration/projects/filter/Makefile
  tests-integration/projects/filter/report.reference_output
  tests-system/lobster-online-report/rbt-valid-flow/valid-scenario/expected-output/exit-code.txt
  tests-system/lobster-online-report/rbt-valid-flow/valid-scenario/expected-output/expected-output.lobster
  tests-system/lobster-online-report/rbt-valid-flow/valid-scenario/expected-output/stderr.txt
  tests-system/lobster-online-report/rbt-valid-flow/valid-scenario/expected-output/stdout.txt
  tests-system/lobster-online-report/rbt-valid-flow/valid-scenario/input/args.txt
  tests-system/lobster-online-report/rbt-valid-flow/valid-scenario/input/basic.py
  tests-system/lobster-online-report/rbt-valid-flow/valid-scenario/input/report.lobster
  tests-system/run_tool_tests.py
  tests-system/tests_utils/update_online_json_with_hashes.py
  tests-unit/lobster-core/online_report/data/basic.py
  tests-unit/lobster-core/online_report/test_online_report.py
  tests-unit/test_items.py
Labels: lobster-core

#188 Write `FILE_OR_DIR` requirement
  lobster/tools/json/software_requirements.trlc
  lobster/tools/json/system_requirements.trlc
  lobster/tools/requirements.rsl
Labels: internal
