Repository bmw-software-engineering/lobster, pull requests merged in 2025-03, with the labels that each got.

#224 Support empty codebeamer queries
  CHANGELOG.md
  lobster/tools/codebeamer/codebeamer.py
  lobster/tools/codebeamer/requirements.trlc
  tests-unit/lobster-codebeamer/test_codebeamer.py
Labels: lobster-codebeamer

#223 Include `graphviz` in `requirements_dev.txt`
  requirements_dev.txt
Labels: internal

#225 Use `SupportedConfigKeys` instead of strings
  lobster/tool.py
Labels: internal

#232 Remove root folder name assertion
  tests-system/testrunner.py
Labels: internal

#228 Implemented STF for lobster-report for status OK
  Makefile
  lobster/tools/core/report/requirements.trlc
  tests-system/.gitignore
  tests-system/asserter.py
  tests-system/lobster-json/lobsterjsontestrunner.py
  tests-system/lobster-report/__init__.py
  tests-system/lobster-report/data/lobster.conf
  tests-system/lobster-report/data/python.lobster
  tests-system/lobster-report/data/report.lobster
  tests-system/lobster-report/data/trlc.lobster
  tests-system/lobster-report/lobster_report_system_test_case_base.py
  tests-system/lobster-report/lobster_report_test_runner.py
  tests-system/lobster-report/rbt-status-ok/all/expected-output/exit-code.txt
  tests-system/lobster-report/rbt-status-ok/all/expected-output/stderr.txt
  tests-system/lobster-report/rbt-status-ok/all/expected-output/stdout.txt
  tests-system/lobster-report/rbt-status-ok/all/input/args.txt
  tests-system/lobster-report/test_status_ok.py
  tests-system/system_test_case_base.py
  tests-system/test_runner.py
Labels: internal

#235 First lint, then test
  .github/workflows/ci.yml
Labels: internal

#240 Remove list of known issues from docu of `lobster-python`
  packages/lobster-tool-python/README.md
Labels: documentation

#239 Fix typo in documentation of `lobster-json`
  packages/lobster-tool-json/README.md
Labels: documentation

#234 Describe how to run system tests with VSCode
  tests-system/README.md
  tests-unit/__init__.py
Labels: internal

#152 Coverage integration test for requirements
  Makefile
  tests-integration/projects/coverage-half/.gitignore
  tests-integration/projects/coverage-half/Makefile
  tests-integration/projects/coverage-half/example.rsl
  tests-integration/projects/coverage-half/lobster.conf
  tests-integration/projects/coverage-half/report.reference_output
  tests-integration/projects/coverage-half/softreq_example.trlc
  tests-integration/projects/coverage-half/sysreq_example.trlc
  tests-integration/projects/coverage-half/trlc-softreq.conf
  tests-integration/projects/coverage-half/trlc-sysreq.conf
  tests-integration/projects/coverage-mix/.gitignore
  tests-integration/projects/coverage-mix/Makefile
  tests-integration/projects/coverage-mix/example.rsl
  tests-integration/projects/coverage-mix/lobster.conf
  tests-integration/projects/coverage-mix/report.reference_output
  tests-integration/projects/coverage-mix/softreq_example.trlc
  tests-integration/projects/coverage-mix/sysreq_example.trlc
  tests-integration/projects/coverage-mix/testreq_example.trlc
  tests-integration/projects/coverage-mix/trlc-softreq.conf
  tests-integration/projects/coverage-mix/trlc-sysreq.conf
  tests-integration/projects/coverage-mix/trlc-testreq.conf
  tests-integration/projects/coverage-zero/.gitignore
  tests-integration/projects/coverage-zero/Makefile
  tests-integration/projects/coverage-zero/example.rsl
  tests-integration/projects/coverage-zero/lobster.conf
  tests-integration/projects/coverage-zero/report.reference_output
  tests-integration/projects/coverage-zero/softreq_example.trlc
  tests-integration/projects/coverage-zero/sysreq_example.trlc
  tests-integration/projects/coverage-zero/trlc-softreq.conf
  tests-integration/projects/coverage-zero/trlc-sysreq.conf
  tests-integration/projects/coverage/.gitignore
  tests-integration/projects/coverage/Makefile
  tests-integration/projects/coverage/example.rsl
  tests-integration/projects/coverage/lobster.conf
  tests-integration/projects/coverage/report.reference_output
  tests-integration/projects/coverage/softreq_example.trlc
  tests-integration/projects/coverage/sysreq_example.trlc
  tests-integration/projects/coverage/trlc-softreq.conf
  tests-integration/projects/coverage/trlc-sysreq.conf
Labels: internal

#241 Implement review comments from PR #152
  tests-integration/projects/coverage-mix/Makefile
  tests-integration/projects/coverage-mix/example.rsl
  tests-integration/projects/coverage-mix/lobster.conf
  tests-integration/projects/coverage-mix/report.reference_output
  tests-integration/projects/coverage-mix/req_a.trlc
  tests-integration/projects/coverage-mix/req_b.trlc
  tests-integration/projects/coverage-mix/softreq_example.trlc
  tests-integration/projects/coverage-mix/sysreq_example.trlc
  tests-integration/projects/coverage-mix/test_spec.trlc
  tests-integration/projects/coverage-mix/testreq_example.trlc
  tests-integration/projects/coverage-mix/trlc-softreq.conf
  tests-integration/projects/coverage-mix/trlc-sysreq.conf
  tests-integration/projects/coverage-mix/trlc_req_a.conf
  tests-integration/projects/coverage-mix/trlc_req_b.conf
  tests-integration/projects/coverage-mix/trlc_test_spec.conf
Labels: internal

#242 Align test names with TRLC package names
  tests-integration/projects/coverage-half/example.rsl
  tests-integration/projects/coverage-half/report.reference_output
  tests-integration/projects/coverage-half/softreq_example.trlc
  tests-integration/projects/coverage-half/sysreq_example.trlc
  tests-integration/projects/coverage-half/trlc-softreq.conf
  tests-integration/projects/coverage-half/trlc-sysreq.conf
  tests-integration/projects/coverage-zero/example.rsl
  tests-integration/projects/coverage-zero/report.reference_output
  tests-integration/projects/coverage-zero/softreq_example.trlc
  tests-integration/projects/coverage-zero/sysreq_example.trlc
  tests-integration/projects/coverage-zero/trlc-softreq.conf
  tests-integration/projects/coverage-zero/trlc-sysreq.conf
Labels: internal

#243 Fix publishment of docs
  .github/workflows/docs.yml
  Makefile
Labels: internal

#245 Requirements for lobster-trlc inputs
  lobster/tools/trlc/input_files.trlc
Labels: internal

#247 Added a test case for combination of inputs and inputs from file
  tests-system/lobster-trlc/data/fruits.rsl
  tests-system/lobster-trlc/data/fruits.trlc
  tests-system/lobster-trlc/data/input_from_files_and_inputs.lobster
  tests-system/lobster-trlc/data/input_from_files_and_inputs.txt
  tests-system/lobster-trlc/data/inputs-from-files-and-inputs.conf
  tests-system/lobster-trlc/test_inputs_and_inputs_from_file.py
Labels: internal

#249 Disable CI for `*.md` files
  .github/workflows/ci.yml
Labels: internal

#250 STF lobste-trlc: inputs from working directory
  tests-system/lobster-trlc/data/input_from_working_directory.lobster
  tests-system/lobster-trlc/lobster_trlc_test_runner.py
  tests-system/lobster-trlc/test_inputs_from_working_directory.py
Labels: internal

#251 Inputs and inputs from file duplicate content scenario test case
  lobster/tools/trlc/input_files.trlc
  tests-system/lobster-trlc/data/input_from_files_and_inputs_duplicate_contents.txt
  tests-system/lobster-trlc/test_input_invalid_extensions.py
  tests-system/lobster-trlc/test_input_list_of_files.py
  tests-system/lobster-trlc/test_inputs_and_inputs_from_file.py
  tests-system/lobster-trlc/test_inputs_from_file.py
Labels: internal

#248 Update installation instructions
  CHANGELOG.md
  README.md
  lobster/tools/codebeamer/codebeamer.py
Labels: documentation

#254 Fix CI Workflow
  .github/workflows/ci.yml
Labels: internal

#259 Use data class for configuration in `codebeamer.py`
  lobster/tools/codebeamer/codebeamer.py
  lobster/tools/codebeamer/config.py
  tests-unit/lobster-codebeamer/test.netrc
  tests-unit/lobster-codebeamer/test_codebeamer.py
  tests-unit/lobster-codebeamer/test_codebeamer_schema.py
Labels: internal

#262 Ensure to run `ci.yml` regardless of the file type
  .github/workflows/ci.yml
Labels: internal

#263 Fix changelog
  CHANGELOG.md
Labels: documentation

#264 LOBSTER Release 0.12.0
  CHANGELOG.md
  lobster/version.py
Labels: internal
